### ISSUE TITLE
10-A

### ISSUE THREAD

**Issue by 172fenbaa** [CapaFenLisesi/IYPT-2017#13]
Hocam sorumuz deneye dayalı olduğundan kaynak bulamıyoruz. Siz de soruyu yazmamızı ve yardım edeceğinizi söylemiştiniz. Sorumuz 1991 yılındaki 'Photograph of a Television Screen' sorusu. Yardımcı olursanız çok seviniriz.

**Comment by ofenerci** [comment]
Hımm.... Ne soru ama! Küçük bir araştırma şöyle bir kaynak verdi. İstersen bir [burdan](https://www.ee.ryerson.ca/~phiscock/astronomy/light-pollution/shutter-cal.pdf) incele.

**Comment by 172fenbaa** [comment]
İlgilendiğiniz için teşekkürler.
